version: '3.8'

services:
  app:
    image: jaiswar203/creatorevolve:latest
    container_name: creatorevolve-api
    ports:
      - "3000:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
