version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped

  app:
    image: jaiswar203/creatorevolve:latest
    container_name: creatorevolve-api
    ports:
      - '3000:8080'
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped
