import {
  IMAGE_ASPECT_RATIO,
  IMAGE_GENERATION_MODEL,
  IMAGE_OUTPUT_FORMAT,
  IMAGE_QUALITY,
  IMAGE_SIZE,
  IMAGE_STYLE,
} from '@/common/constants/image.enum';
import {
  IsBoolean,
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  ValidateIf,
} from 'class-validator';

export class GenerateImageDto {
  @IsString()
  @IsNotEmpty()
  prompt: string;

  @IsBoolean()
  @IsNotEmpty()
  @IsOptional()
  enable_prompt_optimization: boolean = false;

  @IsString()
  @IsOptional()
  negative_prompt: string;

  @IsString()
  @IsOptional()
  stability_aspect_ratio: IMAGE_ASPECT_RATIO; // aspect ratio for the image generated by stable diffusion

  @IsString()
  @IsOptional()
  size: IMAGE_SIZE; // image size of the dall-e

  @IsString()
  @IsNotEmpty()
  @IsEnum(IMAGE_GENERATION_MODEL)
  model: IMAGE_GENERATION_MODEL;

  @ValidateIf((o) => o.model !== IMAGE_GENERATION_MODEL.DALLE)
  @IsString()
  @IsNotEmpty()
  @IsEnum(IMAGE_OUTPUT_FORMAT)
  output_format: IMAGE_OUTPUT_FORMAT;

  @IsNumber()
  @IsOptional()
  number_of_images: number = 1;

  @IsString()
  @IsOptional()
  style: IMAGE_STYLE;

  @IsString()
  @IsOptional()
  quality: IMAGE_QUALITY;
}
