import {
  IMAGE_ASPECT_RATIO,
  IMAGE_GENERATION_MODEL,
  IMAGE_OUTPUT_FORMAT,
  IMAGE_QUALITY,
  IMAGE_SIZE,
  IMAGE_STYLE,
} from '@/common/constants/image.enum';
import {
  IsEnum,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  ValidateIf,
} from 'class-validator';

export class GenerateImageToImageDto {
  @IsString()
  @IsNotEmpty()
  prompt: string;

  @IsString()
  @IsNotEmpty()
  image_url: string;

  @IsString()
  @IsOptional()
  negative_prompt: string;

  @IsString()
  @IsOptional()
  stability_aspect_ratio: IMAGE_ASPECT_RATIO; // aspect ratio for the image generated by stable diffusion

  @IsString()
  @IsNotEmpty()
  @IsEnum(IMAGE_GENERATION_MODEL)
  model: IMAGE_GENERATION_MODEL;

  @ValidateIf((o) => o.model !== IMAGE_GENERATION_MODEL.DALLE)
  @IsString()
  @IsNotEmpty()
  @IsEnum(IMAGE_OUTPUT_FORMAT)
  output_format: IMAGE_OUTPUT_FORMAT;
}
