# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CreatorEvolve Prod Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy production env
        run: cp /home/ubuntu/.env .env.production
        
      - name: Build and push Docker image
        run: |
          docker build -t jaiswar203/creatorevolve:latest .
          docker push jaiswar203/creatorevolve:latest

      - name: Run Docker container
        run: docker compose up -d --build
       
      - name: Logout from Docker Hub
        run: docker logout
